# Generated by Django 5.1 on 2024-11-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='test_field1',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
