# Generated by Django 5.1 on 2024-11-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_testmodel_test_field1'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=81)),
                ('solution', models.CharField(max_length=81)),
                ('time_queried', models.DateTimeField(verbose_name='time_queried')),
            ],
        ),
    ]
