# Generated by Django 5.1 on 2026-02-23 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0004_gamemodel_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=15)),
                ('zip', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
