# Generated by Django 5.1 on 2026-02-23 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0005_flagged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flagged',
            old_name='zip',
            new_name='postal',
        ),
    ]
