# Generated by Django 5.1 on 2026-02-24 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0006_rename_zip_flagged_postal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flagged',
            name='postal',
        ),
    ]
