# Generated by Django 5.1 on 2026-02-24 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0007_remove_flagged_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagged',
            name='postal',
            field=models.CharField(default='00000', max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
            preserve_default=False,
        ),
    ]
