# Generated by Django 5.1 on 2026-02-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0008_flagged_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagged',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flagged',
            name='region',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
